# -*- coding: utf-8 -*-
# Python imports
import logging

# 3rd party imports
# from weasyprint import HTML
from pdfrw import PdfWriter

# App imports

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


# config = pdfkit.configuration(wkhtmltopdf="binaries/wkhtmltopdf")


class PdfRenderer(object):

    # Utility function
    def generate(self, html):
        # result_file2 = open('binaries/wkhtmltopdf', "r")
        # logger.info(result_file2)

        pw = PdfWriter()
        # pw.setFont("Courier", 10)
        # pw.setHeader("Conversion of HTML text to PDF")
        # pw.setFooter("Generated by xtopdf: http://slid.es/vasudevram/xtopdf")
        # pw.
        # Use method chaining this time.
        # for line in BeautifulSoup(html_doc).get_text().split("\n"):
        #     pw.writeLine(line)
        pw.savePage()

        # convert HTML to PDF
        # return HTML(string=html).write_pdf()
        # return pdfkit.from_string(html, False)
        # pisa_status = pisa.CreatePDF(
        #     html  # the HTML to convert
        # )  # file handle to recieve result
        #
        # # close output file
        # # result_file.close()  # close output file

        # return pisa_status.dest
