
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  deploy-3_6: &test-template

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]
            pip install psycopg2

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}


      - store_artifacts:
          path: test-reports
          destination: test-reports

#
#      - run:
#          name: Install Serverless CLI and dependencies
#          command: |
#            sudo npm i -g serverless
#            npm install
#
#      - run:
#          name: Deploy application
#          command: sls deploy --stage pre

workflows:
  version: 2
  test:
    jobs:
      - deploy-3_6